# Generated by Django 3.0.9 on 2020-11-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20201122_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
